
export const projectTemplate = {
    epics: [
        {
            epicId: 1,
            title: "Foundation & Strategic Alignment",
            backlogItems: [
                { title: "Executive Governance Setup", isDescription: true },
                { title: "Establish committee charter and weekly meeting cadence" },
                { title: "Create project management infrastructure and communication protocols" },
                { title: "Customer Research & ICP Redefinition", isDescription: true },
                { title: "Perform current-state analysis" },
                { title: "Execute lost deal analysis" },
                { title: "Perform competitive analysis update and differentiation assessment" },
                { title: "Facilitate cross-functional ICP workshops" },
                { title: "Document detailed ICP including demographics, psychographics, and behaviors" },
                { title: "Value Proposition Development", isDescription: true },
                { title: "Analyze customer research insights for value driver identification" },
                { title: "Conduct value proposition development workshops with stakeholders" },
                { title: "Create unified messaging framework with competitive differentiation" },
                { title: "Develop objection handling and proof point documentation" },
                { title: "Validate messaging with customer feedback and A/B testing" },
                { title: "Cross-Functional Enablement", isDescription: true },
                { title: "Design comprehensive sales enablement program with new messaging" },
                { title: "Realign marketing campaigns and content with updated ICP" },
                { title: "Update all customer-facing materials (proposals, presentations, website)" },
                { title: "Execute internal communication rollout across organization" },
                { title: "Implement messaging consistency measurement and monitoring" },
            ]
        },
        {
            epicId: 2,
            title: "RevOps Foundation & Data Infrastructure",
            backlogItems: [
                { title: "CRM Optimization", isDescription: true },
                { title: "Conduct a comprehensive CRM configuration audit" },
                { title: "Implement data hygiene protocols and validation rules" },
                { title: "Execute systematic data cleansing (prioritizing customer/prospect data)" },
                { title: "Optimize page layouts, custom fields, and user permissions" },
                { title: "System Integration Development", isDescription: true },
                { title: "Map integration architecture and data flow requirements" },
                { title: "Implement priority integrations (Marketing automation, Customer success platform)" },
                { title: "Develop workflow automation (lead routing, opportunity progression)" },
                { title: "Configure automated data synchronization between systems" },
                { title: "Test integrations and establish failure/recovery procedures" },
                { title: "Analytics & Reporting Implementation", isDescription: true },
                { title: "Create real-time performance dashboards for all GTM functions" },
                { title: "Implement automated forecasting system (replace manual Excel processes)" },
                { title: "Deploy advanced lead scoring and customer health monitoring" },
                { title: "Establish KPI tracking with trend analysis and alerts" },
                { title: "Build an executive dashboard with strategic metrics" },
                { title: "Process Documentation & Training", isDescription: true },
                { title: "Document optimized workflows and standard operating procedures" },
                { title: "Create user adoption measurement and feedback systems" },
                { title: "Establish ongoing data quality monitoring and maintenance" },
                { title: "Implement change management support for technology adoption" },
            ]
        },
        {
            epicId: 3,
            title: "Sales Process Enhancement & Pipeline Optimization",
            backlogItems: [
                { title: "Sales Process Standardization", isDescription: true },
                { title: "Map current sales process and identify bottlenecks" },
                { title: "Design optimized sales methodology aligned with customer journey" },
                { title: "Create stage-gate criteria and advancement requirements" },
                { title: "Develop sales playbooks for different customer segments" },
                { title: "Implement opportunity management best practices" },
                { title: "Pipeline Management Enhancement", isDescription: true },
                { title: "Establish pipeline coverage targets (move from 1x to 4x)" },
                { title: "Implement lead qualification framework (improve from <20% to 50% conversion)" },
                { title: "Create pipeline health monitoring and alerts" },
                { title: "Design territory and account assignment optimization" },
                { title: "Establish regular pipeline review cadence and procedures" },
                { title: "Sales Enablement Program", isDescription: true },
                { title: "Create competitive battlecards and positioning materials" },
                { title: "Develop proposal templates and sales collateral library" },
                { title: "Implement sales training on new messaging and processes" },
                { title: "Establish ongoing coaching and skill development programs" },
                { title: "Create performance tracking and improvement plans" },
            ]
        },
        {
            epicId: 4,
            title: "Customer Experience & Lifecycle Management",
            backlogItems: [
                { title: "Customer Journey Mapping & Optimization", isDescription: true },
                { title: "Execute comprehensive customer journey mapping across all touchpoints" },
                { title: "Identify friction points and experience gaps throughout lifecycle" },
                { title: "Develop customer segmentation and persona-based experience paths" },
                { title: "Design onboarding optimization to reduce time-to-value (target: 6+ months to 2 months)" },
                { title: "Create customer journey measurement and monitoring systems" },
                { title: "Proactive Customer Success Implementation", isDescription: true },
                { title: "Implement a customer health scoring system with predictive analytics" },
                { title: "Design proactive customer success workflows and intervention triggers" },
                { title: "Create customer success playbooks (onboarding, adoption, expansion, renewal)" },
                { title: "Establish regular business review cycles and value demonstration" },
                { title: "Build customer communication automation and personalization" },
                { title: "Feedback & Advocacy Programs", isDescription: true },
                { title: "Implement comprehensive feedback system (NPS, CSAT, interviews)" },
                { title: "Create systematic customer feedback analysis and response processes" },
                { title: "Develop customer advocacy and referral programs" },
                { title: "Build a case study and a success story development process" },
                { title: "Establish customer advisory board and strategic relationship programs" },
                { title: "Expansion & Retention Enhancement", isDescription: true },
                { title: "Design account-based marketing campaigns for existing customers" },
                { title: "Create expansion opportunity identification and management processes" },
                { title: "Implement renewal management with early risk identification" },
                { title: "Develop customer value demonstration and ROI reporting" },
                { title: "Build competitive win-back and retention programs" },
            ]
        },
        {
            epicId: 5,
            title: "Performance Measurement & Continuous Optimization",
            backlogItems: [
                { title: "Measurement Framework Implementation", isDescription: true },
                { title: "Establish a comprehensive KPI framework across all GTM domains" },
                { title: "Create performance benchmarking against industry standards" },
                { title: "Implement real-time performance monitoring and alerting" },
                { title: "Design an executive dashboard with key transformation metrics" },
                { title: "Build automated reporting and insight generation" },
                { title: "Analytics & Intelligence Development", isDescription: true },
                { title: "Implement predictive analytics for customer behavior and churn risk" },
                { title: "Deploy competitive intelligence and market positioning optimization" },
                { title: "Create advanced forecasting with scenario planning capabilities" },
                { title: "Build customer lifetime value optimization frameworks" },
                { title: "Establish market opportunity identification and prioritization systems" },
                { title: "Continuous Improvement Process", isDescription: true },
                { title: "Design systematic performance review and optimization cycles" },
                { title: "Create feedback collection and analysis processes" },
                { title: "Implement A/B testing framework for process and messaging optimization" },
                { title: "Establish innovation and experimentation processes" },
                { title: "Build knowledge management and organizational learning systems" },
            ]
        },
        {
            epicId: 6,
            title: "Advanced Capabilities & Scaling",
            backlogItems: [
                { title: "AI & Machine Learning Integration", isDescription: true },
                { title: "Deploy AI-enhanced lead scoring and customer behavior prediction" },
                { title: "Implement conversation intelligence and sales process optimization" },
                { title: "Create predictive customer health and churn modeling" },
                { title: "Build intelligent content and campaign personalization" },
                { title: "Establish automated competitive analysis and response systems" },
                { title: "Advanced Automation & Workflow", isDescription: true },
                { title: "Implement end-to-end customer lifecycle automation" },
                { title: "Create advanced territory and account optimization systems" },
                { title: "Build an intelligent proposal and pricing optimization" },
                { title: "Deploy automated market opportunity identification" },
                { title: "Establish self-healing system monitoring and maintenance" },
                { title: "Strategic Capability Development", isDescription: true },
                { title: "Create market expansion readiness assessment and planning" },
                { title: "Build scalable process frameworks for geographic/segment expansion" },
                { title: "Implement strategic partnership and channel development" },
                { title: "Establish competitive moat development and protection" },
                { title: "Create acquisition integration and synergy realization capabilities" },
            ]
        }
    ]
};
